### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by mmcgreg** [mmcgreg/layout-to-code#1]
@hellachella

[mcgregor-morgan-030-layouttocode-voice.mp3.zip](https://github.com/mmcgreg/layout-to-code/files/5968757/mcgregor-morgan-030-layouttocode-voice.mp3.zip)

😱 😬 ✨ 😎

I hope this is sorta, kinda, pretty close to what this is supposed to sound like...

**Comment by hellachella** [comment]
h1 and nav goes into the header, otherwise golden.
